version: '3.1'

services:

  composer:
    image: composer
    command: install
    volumes:
      - "./:/app"

  php:
    build: .
    ports:
      - "9000:9000"
    volumes:
      - "./:/var/www/html"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://caddy/health.php"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

  autoheal:
    image: willfarrell/autoheal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all

  httpbin:
    image: kong/httpbin

  load:
    image: fortio/fortio
    command: load -t 3m -timeout 3s -allow-initial-errors http://caddy/slow.php
    profiles:
      - test
  
  healthcheck:
    image: curlimages/curl
    command: -v http://caddy/health.php
    profiles:
      - check

  caddy:
    image: caddy
    ports:
      - "80:80"
    volumes:
      - "./Caddyfile:/etc/caddy/Caddyfile"