version: '3.1'

services:

  composer:
    image: composer
    command: install
    volumes:
      - "./:/app"

  php:
    build: .
    ports:
      - "9000:9000"
    volumes:
      - "./:/var/www/html"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://caddy/health.php"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
    cap_add:
      - SYS_PTRACE

  autoheal:
    image: willfarrell/autoheal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all

  httpbin:
    image: kong/httpbin

  load:
    image: fortio/fortio
    command: load -t 3m -timeout 3s -allow-initial-errors http://caddy/slow.php
    profiles:
      - test
  
  healthcheck:
    image: curlimages/curl
    command: -v http://caddy/health.php
    profiles:
      - check

  chunked:
    image: curlimages/curl
    volumes:
      - "./somefile.zip:/tmp/somefile.zip"
    command: '-X POST -T /tmp/somefile.zip -H "Transfer-Encoding: chunked" -v http://caddy263/chunker.php'
    profiles:
      - check

  chunked264:
    image: curlimages/curl
    volumes:
      - "./somefile.zip:/tmp/somefile.zip"
    command: '-X POST -T /tmp/somefile.zip -H "Transfer-Encoding: chunked" -v http://caddy264:81/chunker.php'
    profiles:
      - check

  caddy263:
    image: caddy:2.6.3
    ports:
      - "80:80"
    volumes:
      - "./Caddyfile:/etc/caddy/Caddyfile"

  caddy264:
    image: caddy:2.6.4
    ports:
      - "81:80"
    volumes:
      - "./Caddyfile:/etc/caddy/Caddyfile"